### PR TITLE
Update delete button anchor tag and editor window width

### PR DESCRIPTION
**Pull request by spiropan**
templates/page.html: For delete button removed javascript and added bootstrap modal trigger
templates/editor.html: Line 26 added "class=form-control" so that editor window is loaded at full width.

### CODE REVIEW

**Comment by gouthambs** [comment]
:+1:

**Comment by gouthambs** [comment]
@spiropan 
What is the expected behavior out of using 'form-control' along with markdown editor? The size of the editor is unchanged on my end. Also the full screen works on both (before and after) by clicking the full screen button.

**Comment by spiropan** [comment]
On my end it makes the text area input window the same width as the title
input in the editor.html. Without it is about half the width when the
editor page first loads and I have to manually drag the lower right corner
to make the window the wider. I have overridden the template editor.html
anyways so it's up to you if you want to include the change.

**Comment by gouthambs** [comment]
What browser and OS do you use? Which version of bootstrap are you using? 

When I tested the editor window was the same size as usual but the edges had no borders.

**Comment by spiropan** [comment]
Am on Windows 8.1 and Chrome Version 58.0.3029.110 (64-bit). Bootstrap
version is 3.3.7.  It's loaded earlier and maybe my other css files (i.e.
boostrap-social, custom stylesheets, are overriding?)

On Sat, Jun 24, 2017 at 9:21 AM, Goutham Balaraman <notifications@github.com

**Comment by gouthambs** [comment]
I am not entirely sure why some things don't work on your end. Custom style sheets could be overriding some bootstrap classes which can in turn cause some side effects. For now I will consider this issue closed because you seem to have a work around and the original version works fine in my tests.

**Pull request merged**
