### PR TITLE
Added compatibility with Python 3.4 (fixes #17)

### LINKED ISSUE #17: Support Python 3.X

### PR DESCRIPTION
**Pull request by adilosa**

### CODE REVIEW

**Comment by gouthambs** [comment]
This is awesome. The CI is not hooked to handle python 3. Do you have experience with Travis? Do you think you can get the tests to pass?

**Comment by adilosa** [comment]
I've never worked with Travis before, but I'll see what I can do. I did run the unit tests, and they pass on both Python 2 and Python 3.

**Comment by gouthambs** [comment]
The CI error seems to be in the setup.py script. We don't need any print in there. The `print BASE_PATH` in `setup.py` can be removed . I wonder if the error has to do with this import in the setup script.

**Comment by gouthambs** [comment]
I just tried installing your branch on my system. The error basically says 

``SyntaxError: from __future__ imports must occur at the beginning of the file``

in the `setup.py`. I had the print in the `setup.py` for diagnostic purposes. If you can remove the `print BASE_PATH` and the `print_function` import, I think things should be fine.

**Comment by gouthambs** [comment]
I have added `docs/authors.rst` to keep track of contributors. Would be great if you can add your name to that document along with the pull request.

**Comment by adilosa** [comment]
Awesome, sounds like an easy fix. I'll try to work on this tonight.

**Pull request merged**
