### PR TITLE
Added Google Cloud Datastore support.

### PR DESCRIPTION
**Pull request by agiUnderground**
Hi!

You can also ask [Speedy1991](https://github.com/Speedy1991) to accept my [PR](https://github.com/Speedy1991/Flask-FileUpload/pull/15) and we will have Google Cloud Storage + Google Cloud Datastore support.

### CODE REVIEW

**Comment by gouthambs** [comment]
Thanks. I will take a look later this week.

**Comment by arshak** [comment]
perhaps the example app we should explicitly set FILEUPLOAD_GCS_BUCKET otherwise the user will just get an ACL error about flask_blogging bucket access

**Comment by arshak** [comment]
The example app references 

engine = create_engine('sqlite:////tmp/blog.db')

Why is SQLite db still necessary?

**Comment by agiUnderground** [comment]
> The example app references
> 
> engine = create_engine('sqlite:////tmp/blog.db')
> 
> Why is SQLite db still necessary?

I fixed it.

**Comment by agiUnderground** [comment]
> perhaps the example app we should explicitly set FILEUPLOAD_GCS_BUCKET otherwise the user will just get an ACL error about flask_blogging bucket access

We don't need to do this, the following code ensures that there is a default value(Flask-FileUpload):
```self.bucket_name = app.config.get("FILEUPLOAD_GCS_BUCKET", "flask_fileupload")```

Also check a service account permissions.

**Comment by gouthambs** [comment]
This is  great feature @agiUnderground .. Thanks for your contribution ..

**Pull request merged**
