### PR TITLE
added unicode testcase

### PR DESCRIPTION
**Pull request by slippers**
PR request for unicode in feed.
* change to allow feeds to process unicode text.
* modified test_views adding TestViewsWithUnicode.
* some changes to passing blogger=True flag to login helper function.

### CODE REVIEW

**Comment by gouthambs** [comment]
@slippers 
I am looking at the edits in the test_views.py file. I am not sure I understand why there are all these changes to it. If all we are changing here is adding unicode support to feed, we shouldn't have to change any test for other views I would think. What am I missing here?

**Comment by slippers** [comment]
i'm undoing them:)  seems autoformat broke stuff.

On Fri, Feb 5, 2016 at 11:28 AM, Goutham Balaraman <notifications@github.com

**Comment by gouthambs** [comment]
This patch can be of use to others as well. Thanks for working on this issue. Do you want to try another PR from a fresh branch?

**Comment by slippers** [comment]
trying that now:)

On Fri, Feb 5, 2016 at 12:52 PM, Goutham Balaraman <notifications@github.com

**Pull request closed without merging**
