### PR TITLE
Extension Import Transition

### PR DESCRIPTION
**Pull request by slippers**
[Extension Import Transition](http://flask.pocoo.org/docs/0.11/extensiondev/#extension-import-transition)

just a minor change where the new version of flask shows deprecation warnings.  changed the flask.ext.? to flask_?

### CODE REVIEW

**Comment by gouthambs** [comment]
This is very helpful to keep compatibility to newer Flask versions.

**Comment by gouthambs** [comment]
@slippers So what is the purpose of `update.py`?

**Comment by slippers** [comment]
this file is not needed.  i'll remove.

http://stackoverflow.com/questions/2720014/upgrading-all-packages-with-pip

scraped from stackoverflow.  pushes all the packages to the current version.

On Sun, Jul 3, 2016 at 10:08 PM, Goutham Balaraman <notifications@github.com

**Comment by gouthambs** [comment]
Thanks. Will merge and release soon after.

**Comment by slippers** [comment]
i removed the update.py.

**Comment by slippers** [comment]
branch merged

**Pull request merged**
