### PR TITLE
added img upload to core

### PR DESCRIPTION
**Pull request by Speedy1991**
Depending on #93

### CODE REVIEW

**Comment by Speedy1991** [comment]
`IMG_FOLDER = os.path.join("static", "uploads")`

MUST be present in config, maybe we should add a default location, dunno

**Comment by Speedy1991** [comment]
Hm i'm working on a standalone solution and maybe i'll blueprint this into pypi. You will have to install only my extension/blueprint to your blueprint. It will look exactly the same as the patch i provide in this pr.
Pros:
- less maintenance for you
- seperate blog from image hosting
Cons:
- one more external dependency

**Comment by Speedy1991** [comment]
I put all in a flask extension. I also make a description how to setup with Flask-Blogging. Feel free to install the extension into your core. I think the PR isn't needed except you want to install this fixed version without updates :)
[https://github.com/Speedy1991/Flask-FileUpload](https://github.com/Speedy1991/Flask-FileUpload)

**Comment by gouthambs** [comment]
This should work.

**Comment by Speedy1991** [comment]
Yea, thnx for the hint! I ll close the pr, cause it's not a core feature of blogging. But i ll try to hold it in sync with your madter here for easy integration

**Comment by gouthambs** [comment]
Actually I will merge this feature. It is rather nice to have. Now that you have your extension I can use it instead of repeating all the code here. Do you want to give another PR?

**Comment by Speedy1991** [comment]
Yea, i ll create one this evening or tomorrow

**Pull request closed without merging**
