### PR TITLE
Some Improvements

### PR DESCRIPTION
**Pull request by Speedy1991**
I changed some stuff for my own blog, maybe u can need some fixes and/or improvements.
I also fixed a bug in base.html

### CODE REVIEW

**Comment by gouthambs** [comment]
This looks good. Will take a look and merge.

**Comment by Speedy1991** [comment]
added generic privacy + impressum

**Comment by gouthambs** [comment]
Wondering what is the rationale behind your use of Flask-Security. It doesn't seem like you are using any part of Flask-Security.

**Comment by Speedy1991** [comment]
Flask-Security provides some buildins like login/register/forgot password/... Templates. But i m thinking about building an login_manager injector in my fork of this repo.
E.g. create a security instance and inject the encapsulated login_manager into the blogging engine.
Maybe just drop that change for now and use flask_login. I ll think about a pattern next week

**Comment by gouthambs** [comment]
I am still not sure why we need Flask Security. If one needs the Flask Security features theyvcan use all that outside of Flask Blogging. You would not need to change anything here. Am I missing something?

**Comment by Speedy1991** [comment]
replaced with #99

**Pull request closed without merging**
