### PR TITLE
Replaces #91

### PR DESCRIPTION
**Pull request by Speedy1991**
- FlaskFileupload
- typo fixes
- config was not initialized

### TODO Blogging Site:
- [x] Update example
- [x] Check if the views working as expected - As far i can see all works as expected
- [x] Create a link anywhere to the FileUpload extension
- [x] Copy the blogging/base.html into fileupload/base.html (for getting independend from my base.html)

### TODO FileUpload Site:
- [x]  use flask-login loader instead of authentication callback
- [x] some tests
- [x] check python2, i only write python3.4+

### Update:
Just released [0.4.0](https://github.com/Speedy1991/Flask-FileUpload/tree/0.4.0), should be fine now. I tested python2.7 only with travis

### CODE REVIEW

**Comment by gouthambs** [comment]
:+1:  I can look into merging once you are done with your checklist.

**Comment by Speedy1991** [comment]
I think i ll build the 0.4.0 release the next 48 hours, dunno when i have time

If you have any further suggestions for improvements, just tell me :)

**Comment by gouthambs** [comment]
The flask-fileupload plugin looks fabulous. This is a much needed feature that has finally materialized. I noticed a bug, I will file an issue on your github project page.

**Comment by gouthambs** [comment]
@Speedy1991 @seanpianka New version 0.8.0 posted. Thanks for all your help.

**Pull request merged**
